# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 09:16
from __future__ import unicode_literals

import app.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover',
            field=models.ImageField(default='cover/default.jpg', max_length=255, upload_to=app.user.models._path_to_cover),
        ),
    ]
