# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_profile_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='profile_create',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_create', to='user.Profile'),
        ),
    ]
