# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20151231_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
