# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='date_level',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='friend',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
